### ISSUE TITLE
No colored ascii in Ubuntu 14.04 LTS terminal

### ISSUE THREAD

**Issue by ChrisCalderon** [mofarrell/p2pvc#1]
Alos, it would be nice if you add to your README that ubuntu users should do the following to install dependencies:
`sudo apt-get install libncurses-dev libopencv-dev libpulse-dev`

**Comment by emgram769** [comment]
what terminal emulator are you using? does it default to black and white? what is the output of `echo $TERM`?

I'll add the ncurses to the dependencies list, thanks

**Comment by ChrisCalderon** [comment]
My terminal emulator is GNOME Terminal 3.6.2, the standard terminal in Ubuntu. My `TERM` is xterm-color.

**Comment by emgram769** [comment]
try `export TERM=xterm-color256`. xterm-color seems to only support 16 colors, which defaults to black and white in p2pvc.

**Comment by ChrisCalderon** [comment]
That worked! haha, nice!

**Comment by emgram769** [comment]
:)
