### ISSUE TITLE
too much noise

### ISSUE THREAD

**Issue by c02y** [mofarrell/p2pvc#15]
After `./p2pvc 127.0.0.1 -v` in terminal, too much noise. No mic or speakers plugged, not mute the sound.

**Comment by emgram769** [comment]
I'm confused by what you mean.  If the speakers are not plugged in, how is there any noise at all?

**Comment by c02y** [comment]
Oh, sorry, I mean the builtin JBL speakers on my laptop.

**Comment by mofarrell** [comment]
There is probably feedback from the mic on your laptop.  Use headphones.

**Comment by c02y** [comment]
It is much better using headphone. Thanks.
