### ISSUE TITLE
Issue with installing on ubuntu 14.04

### ISSUE THREAD

**Issue by robincsamuel** [mofarrell/p2pvc#21]
gcc -Isrc/inc -O2 -Wall -DPA_USE_ALSA pkg-config --cflags opencv src/audio.c -c -o objs/audio.o
\In file included from src/audio.c:36:0:
src/inc/pa_util.h:78:9: error: unknown type name ‘PaHostApiTypeId’
PaHostApiTypeId type );
^
src/inc/pa_util.h:91:9: error: unknown type name ‘PaDeviceIndex’
PaDeviceIndex hostApiDevice, PaDeviceIndex device,
^
src/inc/pa_util.h:91:39: error: unknown type name ‘PaDeviceIndex’
PaDeviceIndex _hostApiDevice, PaDeviceIndex device,
^
src/inc/pa_util.h:111:35: error: unknown type name ‘PaHostApiTypeId’
void PaUtil_SetLastHostErrorInfo( PaHostApiTypeId hostApiType, long errorCode,
^
src/audio.c:90:5: error: unknown type name ‘PaStreamCallbackTimeInfo’
const PaStreamCallbackTimeInfo timeInfo,
^
src/audio.c:91:5: error: unknown type name ‘PaStreamCallbackFlags’
PaStreamCallbackFlags statusFlags,
^
src/audio.c:114:5: error: unknown type name ‘PaStreamCallbackTimeInfo’
const PaStreamCallbackTimeInfo_ timeInfo,
^
src/audio.c:115:5: error: unknown type name ‘PaStreamCallbackFlags’
PaStreamCallbackFlags statusFlags,
^
src/audio.c: In function ‘start_audio’:
src/audio.c:169:3: error: unknown type name ‘PaStreamParameters’
PaStreamParameters inputParameters,
^
src/audio.c:212:19: error: request for member ‘device’ in something not a structure or union
outputParameters.device = Pa_GetDefaultOutputDevice(); /\* default output device /
^
src/audio.c:212:3: warning: implicit declaration of function ‘Pa_GetDefaultOutputDevice’ [-Wimplicit-function-declaration]
outputParameters.device = Pa_GetDefaultOutputDevice(); / default output device /
^
src/audio.c:213:23: error: request for member ‘device’ in something not a structure or union
if (outputParameters.device == paNoDevice) {
^
src/audio.c:217:19: error: request for member ‘channelCount’ in something not a structure or union
outputParameters.channelCount = NUM_CHANNELS;
^
src/audio.c:218:19: error: request for member ‘sampleFormat’ in something not a structure or union
outputParameters.sampleFormat = PA_SAMPLE_TYPE;
^
src/audio.c:219:19: error: request for member ‘suggestedLatency’ in something not a structure or union
outputParameters.suggestedLatency = Pa_GetDeviceInfo(outputParameters.device)->defaultLowOutputLatency;
^
src/audio.c:219:72: error: request for member ‘device’ in something not a structure or union
outputParameters.suggestedLatency = Pa_GetDeviceInfo(outputParameters.device)->defaultLowOutputLatency;
^
src/audio.c:220:19: error: request for member ‘hostApiSpecificStreamInfo’ in something not a structure or union
outputParameters.hostApiSpecificStreamInfo = NULL;
^
src/audio.c:229:7: error: ‘writeCallback’ undeclared (first use in this function)
writeCallback,
^
src/audio.c:229:7: note: each undeclared identifier is reported only once for each function it appears in
src/audio.c:230:7: warning: passing argument 2 of ‘Pa_OpenStream’ makes integer from pointer without a cast [enabled by default]
&data);
^
In file included from src/audio.c:34:0:
/usr/include/portaudio.h:325:9: note: expected ‘PaDeviceID’ but argument is of type ‘void _’
PaError Pa_OpenStream( PortAudioStream_ stream,
^
src/audio.c:230:7: warning: passing argument 3 of ‘Pa_OpenStream’ makes integer from pointer without a cast [enabled by default]
&data);
^
In file included from src/audio.c:34:0:
/usr/include/portaudio.h:325:9: note: expected ‘int’ but argument is of type ‘int ’
PaError Pa_OpenStream( PortAudioStream\* stream,
^
src/audio.c:230:7: warning: passing argument 5 of ‘Pa_OpenStream’ makes pointer from integer without a cast [enabled by default]
&data);
^
In file included from src/audio.c:34:0:
/usr/include/portaudio.h:325:9: note: expected ‘void ’ but argument is of type ‘int’
PaError Pa_OpenStream( PortAudioStream\* stream,
^
src/audio.c:230:7: warning: passing argument 8 of ‘Pa_OpenStream’ makes integer from pointer without a cast [enabled by default]
&data);
^
In file included from src/audio.c:34:0:
/usr/include/portaudio.h:325:9: note: expected ‘PaSampleFormat’ but argument is of type ‘struct paTestData ’
PaError Pa_OpenStream( PortAudioStream\* stream,
^
src/audio.c:230:7: error: too few arguments to function ‘Pa_OpenStream’
&data);
^
In file included from src/audio.c:34:0:
/usr/include/portaudio.h:325:9: note: declared here
PaError Pa_OpenStream( PortAudioStream*\* stream,
^
src/audio.c:235:18: error: request for member ‘device’ in something not a structure or union
inputParameters.device = Pa_GetDefaultInputDevice(); /\* default input device /
^
src/audio.c:235:3: warning: implicit declaration of function ‘Pa_GetDefaultInputDevice’ [-Wimplicit-function-declaration]
inputParameters.device = Pa_GetDefaultInputDevice(); / default input device /
^
src/audio.c:236:22: error: request for member ‘device’ in something not a structure or union
if (inputParameters.device == paNoDevice) {
^
src/audio.c:240:18: error: request for member ‘channelCount’ in something not a structure or union
inputParameters.channelCount = NUM_CHANNELS;
^
src/audio.c:241:18: error: request for member ‘sampleFormat’ in something not a structure or union
inputParameters.sampleFormat = PA_SAMPLE_TYPE;
^
src/audio.c:242:18: error: request for member ‘suggestedLatency’ in something not a structure or union
inputParameters.suggestedLatency = Pa_GetDeviceInfo(inputParameters.device)->defaultLowInputLatency;
^
src/audio.c:242:70: error: request for member ‘device’ in something not a structure or union
inputParameters.suggestedLatency = Pa_GetDeviceInfo(inputParameters.device)->defaultLowInputLatency;
^
src/audio.c:243:18: error: request for member ‘hostApiSpecificStreamInfo’ in something not a structure or union
inputParameters.hostApiSpecificStreamInfo = NULL;
^
src/audio.c:252:7: error: ‘readCallback’ undeclared (first use in this function)
readCallback,
^
src/audio.c:253:7: warning: passing argument 2 of ‘Pa_OpenStream’ makes integer from pointer without a cast [enabled by default]
&data);
^
In file included from src/audio.c:34:0:
/usr/include/portaudio.h:325:9: note: expected ‘PaDeviceID’ but argument is of type ‘int _’
PaError Pa_OpenStream( PortAudioStream_ stream,
^
src/audio.c:253:7: warning: passing argument 3 of ‘Pa_OpenStream’ makes integer from pointer without a cast [enabled by default]
&data);
^
In file included from src/audio.c:34:0:
/usr/include/portaudio.h:325:9: note: expected ‘int’ but argument is of type ‘void ’
PaError Pa_OpenStream( PortAudioStream\* stream,
^
src/audio.c:253:7: warning: passing argument 5 of ‘Pa_OpenStream’ makes pointer from integer without a cast [enabled by default]
&data);
^
In file included from src/audio.c:34:0:
/usr/include/portaudio.h:325:9: note: expected ‘void ’ but argument is of type ‘int’
PaError Pa_OpenStream( PortAudioStream\* stream,
^
src/audio.c:253:7: warning: passing argument 8 of ‘Pa_OpenStream’ makes integer from pointer without a cast [enabled by default]
&data);
^
In file included from src/audio.c:34:0:
/usr/include/portaudio.h:325:9: note: expected ‘PaSampleFormat’ but argument is of type ‘struct paTestData ’
PaError Pa_OpenStream( PortAudioStream\* stream,
^
src/audio.c:253:7: error: too few arguments to function ‘Pa_OpenStream’
&data);
^
In file included from src/audio.c:34:0:
/usr/include/portaudio.h:325:9: note: declared here
PaError Pa_OpenStream( PortAudioStream*\* stream,
^
make: **\* [objs/audio.o] Error 1

**Comment by emgram769** [comment]
please install portaudio19-dev

**Comment by robincsamuel** [comment]
Thanks! It solved the above issue. I would like to suggest you to update readme with portaudio19-dev insallation tips.

And I got another error,

gcc -Isrc/inc -O2 -Wall -DPA_USE_ALSA `pkg-config --cflags opencv` objs/audio.o objs/display.o objs/p2plib.o objs/p2pvc.o objs/pa_allocation.o objs/pa_converters.o objs/pa_cpuload.o objs/pa_debugprint.o objs/pa_dither.o objs/pa_front.o objs/pa_process.o objs/pa_ringbuffer.o objs/pa_stream.o objs/pa_trace.o objs/pa_unix_hostapis.o objs/pa_unix_util.o objs/video.o -o p2pvc -lpthread -lncurses -lportaudio `pkg-config --libs opencv`
/usr/bin/ld: objs/pa_unix_util.o: undefined reference to symbol 'floor@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: **\* [p2pvc] Error 1

**Comment by emgram769** [comment]
I've updated the readme already in response to #14. pull the latest version of the Makefile to resolve your current issue
