### ISSUE TITLE
Feature Request: Use Terminal Colors

### ISSUE THREAD

**Issue by Pinwheeler** [mofarrell/p2pvc#24]
Is there some way to choose to not color each character in favor of the current terminal's color scheme? My friends and coworkers really like the "matrix mode" factor, but they want to see themselves in pure, unadulterated green.

**Comment by emgram769** [comment]
you can now set custom colors using the `-c` flag. check the readme for more info

`./p2pvc 127.0.0.1 -v -c 0:100:0`

**Comment by Pinwheeler** [comment]
sweeeeeeeet
