### ISSUE TITLE
OSX 10.10.1

### ISSUE THREAD

**Issue by txthinking** [mofarrell/p2pvc#29]
```
FUCK:p2pvc tx$ brew install ncurses portaudio opencv
Warning: ncurses-5.9 already installed
Warning: portaudio-19.20140130 already installed
Warning: opencv-2.4.10.1 already installed

FUCK:p2pvc tx$ git log | grep commit | head -n 1
commit 53deb08bc1904171ae777f337be781f93f174063

FUCK:p2pvc tx$ make
uname: illegal option -- o
usage: uname [-amnprsv]
gcc -Isrc/inc -O2 -Wall -DPA_USE_COREAUDIO `pkg-config --cflags opencv` src/audio.c -c -o objs/audio.o
src/audio.c:34:10: fatal error: 'portaudio.h' file not found
#include <portaudio.h>
         ^
1 error generated.
make: *** [objs/audio.o] Error 1
```

**Comment by emgram769** [comment]
when in doubt, `sudo find / -name "portaudio.h"`

**Comment by txthinking** [comment]
FUCK:p2pvc tx$ sudo find / -name "portaudio.h"
Password:
find: /dev/fd/3: Not a directory
find: /dev/fd/4: Not a directory
/usr/local/Cellar/portaudio/19.20140130/include/portaudio.h
/usr/local/include/portaudio.h

so how to do next?

On Thu, Feb 12, 2015 at 12:01 PM, emgram769 notifications@github.com
wrote:

> when in doubt, sudo find / -name "portaudio.h"
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mofarrell/p2pvc/issues/29#issuecomment-74014069.

## 

About Me: http://www.txthinking.com

**Comment by emgram769** [comment]
`export C_INCLUDE_PATH=/usr/local/Cellar/portaudio/19.20140130/include:/usr/local/include; make clean; make`

**Comment by txthinking** [comment]
FUCK:p2pvc tx$ export
C_INCLUDE_PATH=/usr/local/Cellar/portaudio/19.20140130/include:/usr/local/include;
make clean; make
uname: illegal option -- o
usage: uname [-amnprsv]
rm -rf objs audio video p2pvc
uname: illegal option -- o
usage: uname [-amnprsv]
mkdir -p objs
gcc -Isrc/inc -O2 -Wall -DPA_USE_COREAUDIO `pkg-config --cflags opencv`
src/audio.c -c -o objs/audio.o
gcc -Isrc/inc -O2 -Wall -DPA_USE_COREAUDIO `pkg-config --cflags opencv`
src/display.c -c -o objs/display.o
gcc -Isrc/inc -O2 -Wall -DPA_USE_COREAUDIO `pkg-config --cflags opencv`
src/p2plib.c -c -o objs/p2plib.o
src/p2plib.c:21:24: warning: unused variable 'prevPacket'
[-Wunused-variable]
static struct timespec prevPacket, currPacket;
                       ^
src/p2plib.c:21:36: warning: unused variable 'currPacket'
[-Wunused-variable]
static struct timespec prevPacket, currPacket;
                                   ^
src/p2plib.c:22:13: warning: unused variable 'delta' [-Wunused-variable]
static long delta = -1;
            ^
src/p2plib.c:23:21: warning: unused variable 'bandwidth_index'
[-Wunused-variable]
static unsigned int bandwidth_index;
                    ^
4 warnings generated.
gcc -Isrc/inc -O2 -Wall -DPA_USE_COREAUDIO `pkg-config --cflags opencv`
src/p2pvc.c -c -o objs/p2pvc.o
src/p2pvc.c:42:25: warning: sizeof on array function parameter will return
size of 'char _' instead of 'char []'
      [-Wsizeof-array-argument]
  for (i = 0; i < sizeof(dim); i++) {
                        ^
src/p2pvc.c:39:26: note: declared here
void get_dimensions(char dim[], int *width, int *height) {
                         ^
src/p2pvc.c:43:60: warning: sizeof on array function parameter will return
size of 'char *' instead of 'char []'
      [-Wsizeof-array-argument]
    if ((dim[i] == 'x' || dim[i] == ':') && (i + 1 < sizeof(dim))) {
                                                           ^
src/p2pvc.c:39:26: note: declared here
void get_dimensions(char dim[], int *width, int *height) {
                         ^
2 warnings generated.
gcc -Isrc/inc -O2 -Wall -DPA_USE_COREAUDIO `pkg-config --cflags opencv`
src/pa_allocation.c -c -o objs/pa_allocation.o
gcc -Isrc/inc -O2 -Wall -DPA_USE_COREAUDIO `pkg-config --cflags opencv`
src/pa_converters.c -c -o objs/pa_converters.o
gcc -Isrc/inc -O2 -Wall -DPA_USE_COREAUDIO `pkg-config --cflags opencv`
src/pa_cpuload.c -c -o objs/pa_cpuload.o
gcc -Isrc/inc -O2 -Wall -DPA_USE_COREAUDIO `pkg-config --cflags opencv`
src/pa_debugprint.c -c -o objs/pa_debugprint.o
gcc -Isrc/inc -O2 -Wall -DPA_USE_COREAUDIO `pkg-config --cflags opencv`
src/pa_dither.c -c -o objs/pa_dither.o
gcc -Isrc/inc -O2 -Wall -DPA_USE_COREAUDIO `pkg-config --cflags opencv`
src/pa_front.c -c -o objs/pa_front.o
gcc -Isrc/inc -O2 -Wall -DPA_USE_COREAUDIO `pkg-config --cflags opencv`
src/pa_process.c -c -o objs/pa_process.o
gcc -Isrc/inc -O2 -Wall -DPA_USE_COREAUDIO `pkg-config --cflags opencv`
src/pa_ringbuffer.c -c -o objs/pa_ringbuffer.o
gcc -Isrc/inc -O2 -Wall -DPA_USE_COREAUDIO `pkg-config --cflags opencv`
src/pa_stream.c -c -o objs/pa_stream.o
gcc -Isrc/inc -O2 -Wall -DPA_USE_COREAUDIO `pkg-config --cflags opencv`
src/pa_trace.c -c -o objs/pa_trace.o
gcc -Isrc/inc -O2 -Wall -DPA_USE_COREAUDIO `pkg-config --cflags opencv`
src/pa_unix_hostapis.c -c -o objs/pa_unix_hostapis.o
gcc -Isrc/inc -O2 -Wall -DPA_USE_COREAUDIO `pkg-config --cflags opencv`
src/pa_unix_util.c -c -o objs/pa_unix_util.o
gcc -Isrc/inc -O2 -Wall -DPA_USE_COREAUDIO `pkg-config --cflags opencv`
src/video.c -c -o objs/video.o
In file included from src/video.c:1:
In file included from /usr/local/Cellar/opencv/
2.4.10.1/include/opencv/cv.h:63:
In file included from /usr/local/Cellar/opencv/
2.4.10.1/include/opencv2/core/core_c.h:47:
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/types_c.h:343:17:
warning: unused function 'cvFloor' [-Wunused-function]
CV_INLINE  int  cvFloor( double value )
                ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/types_c.h:360:17:
warning: unused function 'cvCeil' [-Wunused-function]
CV_INLINE  int  cvCeil( double value )
                ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/types_c.h:379:15:
warning: unused function 'cvIsNaN' [-Wunused-function]
CV_INLINE int cvIsNaN( double value )
              ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/types_c.h:388:15:
warning: unused function 'cvIsInf' [-Wunused-function]
CV_INLINE int cvIsInf( double value )
              ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/types_c.h:403:17:
warning: unused function 'cvRNG' [-Wunused-function]
CV_INLINE CvRNG cvRNG( int64 seed CV_DEFAULT(-1))
                ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/types_c.h:419:18:
warning: unused function 'cvRandReal'
      [-Wunused-function]
CV_INLINE double cvRandReal( CvRNG_ rng )
                 ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/types_c.h:733:17:
warning: unused function 'cvMat' [-Wunused-function]
CV_INLINE CvMat cvMat( int rows, int cols, int type, void\* data
CV_DEFAULT(NULL))
                ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/types_c.h:763:20:
warning: unused function 'cvmGet' [-Wunused-function]
CV_INLINE  double  cvmGet( const CvMat\* mat, int row, int col )
                   ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/types_c.h:781:18:
warning: unused function 'cvmSet' [-Wunused-function]
CV_INLINE  void  cvmSet( CvMat\* mat, int row, int col, double value )
                 ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/types_c.h:798:15:
warning: unused function 'cvIplDepth'
      [-Wunused-function]
CV_INLINE int cvIplDepth( int type )
              ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/types_c.h:973:20:
warning: unused function 'cvRectToROI'
      [-Wunused-function]
CV_INLINE  IplROI  cvRectToROI( CvRect rect, int coi )
                   ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/types_c.h:986:20:
warning: unused function 'cvROIToRect'
      [-Wunused-function]
CV_INLINE  CvRect  cvROIToRect( IplROI roi )
                   ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/types_c.h:1007:28:
warning: unused function 'cvTermCriteria'
      [-Wunused-function]
CV_INLINE  CvTermCriteria  cvTermCriteria( int type, int max_iter, double
epsilon )
                           ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/types_c.h:1029:21:
warning: unused function 'cvPoint'
      [-Wunused-function]
CV_INLINE  CvPoint  cvPoint( int x, int y )
                    ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/types_c.h:1059:26:
warning: unused function 'cvPointTo32f'
      [-Wunused-function]
CV_INLINE  CvPoint2D32f  cvPointTo32f( CvPoint point )
                         ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/types_c.h:1084:26:
warning: unused function 'cvPoint3D32f'
      [-Wunused-function]
CV_INLINE  CvPoint3D32f  cvPoint3D32f( double x, double y, double z )
                         ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/types_c.h:1104:26:
warning: unused function 'cvPoint2D64f'
      [-Wunused-function]
CV_INLINE  CvPoint2D64f  cvPoint2D64f( double x, double y )
                         ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/types_c.h:1124:26:
warning: unused function 'cvPoint3D64f'
      [-Wunused-function]
CV_INLINE  CvPoint3D64f  cvPoint3D64f( double x, double y, double z )
                         ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/types_c.h:1163:25:
warning: unused function 'cvSize2D32f'
      [-Wunused-function]
CV_INLINE  CvSize2D32f  cvSize2D32f( double width, double height )
                        ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/types_c.h:1239:22:
warning: unused function 'cvRealScalar'
      [-Wunused-function]
CV_INLINE  CvScalar  cvRealScalar( double val0 )
                     ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/types_c.h:1247:22:
warning: unused function 'cvScalarAll'
      [-Wunused-function]
CV_INLINE  CvScalar  cvScalarAll( double val0123 )
                     ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/types_c.h:1762:22:
warning: unused function 'cvAttrList'
      [-Wunused-function]
CV_INLINE CvAttrList cvAttrList( const char*\* attr CV_DEFAULT(NULL),
                     ^
In file included from src/video.c:1:
In file included from /usr/local/Cellar/opencv/
2.4.10.1/include/opencv/cv.h:63:
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/core_c.h:127:18:
warning: unused function 'cvDecRefData'
      [-Wunused-function]
CV_INLINE  void  cvDecRefData( CvArr\* arr )
                 ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/core_c.h:148:17:
warning: unused function 'cvIncRefData'
      [-Wunused-function]
CV_INLINE  int  cvIncRefData( CvArr\* arr )
                ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/core_c.h:182:20:
warning: unused function 'cvGetRow' [-Wunused-function]
CV_INLINE  CvMat\*  cvGetRow( const CvArr\* arr, CvMat\* submat, int row )
                   ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/core_c.h:193:20:
warning: unused function 'cvGetCol' [-Wunused-function]
CV_INLINE  CvMat\*  cvGetCol( const CvArr\* arr, CvMat\* submat, int col )
                   ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/core_c.h:222:18:
warning: unused function 'cvReleaseMatND'
      [-Wunused-function]
CV_INLINE  void  cvReleaseMatND( CvMatND*\* mat )
                 ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/core_c.h:245:25:
warning: unused function 'cvGetNextSparseNode'
      [-Wunused-function]
CV_INLINE CvSparseNode\* cvGetNextSparseNode( CvSparseMatIterator*
mat_iterator )
                        ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/core_c.h:495:18:
warning: unused function 'cvSubS' [-Wunused-function]
CV_INLINE  void  cvSubS( const CvArr\* src, CvScalar value, CvArr\* dst,
                 ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/core_c.h:1057:18:
warning: unused function 'cvCloneSeq'
      [-Wunused-function]
CV_INLINE CvSeq\* cvCloneSeq( const CvSeq\* seq, CvMemStorage\* storage
CV_DEFAULT(NULL))
                 ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/core_c.h:1100:23:
warning: unused function 'cvSetNew'
      [-Wunused-function]
CV_INLINE  CvSetElem\* cvSetNew( CvSet\* set_header )
                      ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/core_c.h:1115:17:
warning: unused function 'cvSetRemoveByPtr'
      [-Wunused-function]
CV_INLINE  void cvSetRemoveByPtr( CvSet\* set_header, void\* elem )
                ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/core_c.h:1130:22:
warning: unused function 'cvGetSetElem'
      [-Wunused-function]
CV_INLINE CvSetElem\* cvGetSetElem( const CvSet\* set_header, int idx )
                     ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/core_c.h:1302:18:
warning: unused function 'cvEllipseBox'
      [-Wunused-function]
CV_INLINE  void  cvEllipseBox( CvArr\* img, CvBox2D box, CvScalar color,
                 ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/core_c.h:1398:18:
warning: unused function 'cvFont' [-Wunused-function]
CV_INLINE CvFont cvFont( double scale, int thickness CV_DEFAULT(1) )
                 ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/core_c.h:1601:15:
warning: unused function 'cvReadIntByName'
      [-Wunused-function]
CV_INLINE int cvReadIntByName( const CvFileStorage\* fs, const CvFileNode*
map,
              ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/core_c.h:1616:18:
warning: unused function 'cvReadRealByName'
      [-Wunused-function]
CV_INLINE double cvReadRealByName( const CvFileStorage\* fs, const
CvFileNode\* map,
                 ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/core_c.h:1630:23:
warning: unused function 'cvReadStringByName'
      [-Wunused-function]
CV_INLINE const char\* cvReadStringByName( const CvFileStorage\* fs, const
CvFileNode\* map,
                      ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/core/core_c.h:1642:17:
warning: unused function 'cvReadByName'
      [-Wunused-function]
CV_INLINE void\* cvReadByName( CvFileStorage\* fs, const CvFileNode\* map,
                ^
In file included from src/video.c:1:
In file included from /usr/local/Cellar/opencv/
2.4.10.1/include/opencv/cv.h:65:
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/imgproc/imgproc_c.h:362:18:
warning: unused function 'cvContourPerimeter'
      [-Wunused-function]
CV_INLINE double cvContourPerimeter( const void\* contour )
                 ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/imgproc/imgproc_c.h:486:18:
warning: unused function 'cvCalcHist'
      [-Wunused-function]
CV_INLINE  void  cvCalcHist( IplImage*\* image, CvHistogram\* hist,
                 ^
In file included from src/video.c:1:
In file included from /usr/local/Cellar/opencv/
2.4.10.1/include/opencv/cv.h:72:
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/legacy/compat.hpp:617:23:
warning: unused function 'cvSURFPoint'
      [-Wunused-function]
CV_INLINE CvSURFPoint cvSURFPoint( CvPoint2D32f pt, int laplacian,
                      ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/legacy/compat.hpp:698:26:
warning: unused function 'cvStarKeypoint'
      [-Wunused-function]
CV_INLINE CvStarKeypoint cvStarKeypoint(CvPoint pt, int size, float
response)
                         ^
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/legacy/compat.hpp:716:32:
warning: unused function 'cvStarDetectorParams'
      [-Wunused-function]
CV_INLINE CvStarDetectorParams cvStarDetectorParams(
                               ^
In file included from src/video.c:2:
In file included from /usr/local/Cellar/opencv/
2.4.10.1/include/opencv/highgui.h:47:
/usr/local/Cellar/opencv/2.4.10.1/include/opencv2/highgui/highgui_c.h:589:15:
warning: unused function 'CV_FOURCC'
      [-Wunused-function]
CV_INLINE int CV_FOURCC(char c1, char c2, char c3, char c4)
              ^
45 warnings generated.
gcc -Isrc/inc -O2 -Wall -DPA_USE_COREAUDIO `pkg-config --cflags opencv`
objs/audio.o objs/display.o objs/p2plib.o objs/p2pvc.o objs/pa_allocation.o
objs/pa_converters.o objs/pa_cpuload.o objs/pa_debugprint.o
objs/pa_dither.o objs/pa_front.o objs/pa_process.o objs/pa_ringbuffer.o
objs/pa_stream.o objs/pa_trace.o objs/pa_unix_hostapis.o
objs/pa_unix_util.o objs/video.o -o p2pvc -lpthread -lncurses -lportaudio
-lm `pkg-config --libs opencv`
ld: library not found for -lportaudio
clang: error: linker command failed with exit code 1 (use -v to see
invocation)
make: **\* [p2pvc] Error 1

On Thu, Feb 12, 2015 at 12:08 PM, emgram769 notifications@github.com
wrote:

> export
> C_INCLUDE_PATH=/usr/local/Cellar/portaudio/19.20140130/include:/usr/local/include;
> make clean; make
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mofarrell/p2pvc/issues/29#issuecomment-74014560.

## 

About Me: http://www.txthinking.com

**Comment by emgram769** [comment]
`brew uninstall portaudio --force; brew install portaudio` and then try the previous command again.

**Comment by txthinking** [comment]
ld: library not found for -lportaudio

On Thu, Feb 12, 2015 at 12:20 PM, emgram769 notifications@github.com
wrote:

> brew uninstall portaudio --force; brew install portaudio
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mofarrell/p2pvc/issues/29#issuecomment-74015316.

## 

About Me: http://www.txthinking.com

**Comment by emgram769** [comment]
ultimately this does not pertain to p2pvc but rather your personal installation of portaudio, so I'm gonna close this.  I'm not sure what else you could try but perhaps someone with OS X might be able to help out.

**Comment by amitv87** [comment]
export LIBRARY_PATH="/usr/local/lib" should solvethe issue  ld: library not found for -lportaudio
