### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [mofarrell/p2pvc#36]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/mofarrell/p2pvc/blob/16086cf6837d882bd07de2fc0464d008e99e1e37/Makefile#L1) so that powerful checks for software features will become easier.
- [CMake](http://cmake.org/)
- [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction)

**Comment by jirutka** [comment]
Why the hell you wanna replace small and well readable make file with an autotools madness?! :pouting_cat:

**Comment by ryanmjacobs** [comment]
Yeah, I agree with @jirutka. The current makefile is already so small and clean! :grin:

Why fix something that ain't broke?

**Comment by elfring** [comment]
- Does [a tool like "autoscan"](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html) show any software dependencies that you find worth for further considerations?
- How do you think about to support more development environments by [the reuse of build system generators](http://www.cmake.org/cmake/help/v3.1/manual/cmake-generators.7.html#introduction)?

**Comment by jirutka** [comment]
The current simple makefile works for both GNU/Linux and OS X (basically FreeBSD, so it'll probably work even on other BSDs). It seems good for me, no reason to mess it with autotools insanity.
