### ISSUE TITLE
custom font for better quality video?

### ISSUE THREAD

**Issue by jose1711** [mofarrell/p2pvc#37]
would it be possible to adopt one of the libcaca's todos (http://caca.zoy.org/browser/libcaca/trunk/TODO?rev=676)?
allow to select the characters that will be used for bitmap
12       rendering, for instance halftoning (░ ▒ ▓ █) and quarter
13       blocks (▀ ▄ ▌ ▐ █ ▖ ▗ ▘ ▝ ▚ ▞ ▙ ▛ ▜ ▟).

not sure if this could extend into: create a custom font (x11/ttf) that would allow for downscaled but very accurate version of bi-color image). in theory unicode has support for 65536 characters, so having a 3x5 (2^15) grid could be possible.

**Comment by emgram769** [comment]
already done. check the `-a` flag in the readme.  partial blocks is implemented in braille (gives a finer granularity than the quarter blocks), see the `-B` flag.

**Comment by jose1711** [comment]
thank you, please what combination of font + terminal do you recommend for braille?

**Comment by jose1711** [comment]
also i wonder whether you've been experimenting with a 1x1 pixel font. i believe this combined with color could be pretty interesting (while most likely very cpu demanding)

**Comment by emgram769** [comment]
I just use source code pro + urxvt for braille (the result is pretty good and demoed in the readme).  what is a 1x1 pixel font?

**Comment by jose1711** [comment]
a 1 pixel font is basically a "font", where one character is mapped to a pixel-wide glyph. not sure if there's a ttf equivalent but i created such font easily for console. then you describe each and every pixel with a single character. as i said, that could be pretty intensive and maybe not even work on non-framebuffer terminals (will try to test it).
