### ISSUE TITLE
OS X 10.10.4 

### ISSUE THREAD

**Issue by vijayanandrp** [mofarrell/p2pvc#39]
JARVIS:Desktop admin$ brew install portaudio
Warning: portaudio-19.20140130 already installed, it's just not linked

---

JARVIS:Desktop admin$ sudo easy_install PyAudio
Searching for PyAudio
Reading https://pypi.python.org/simple/PyAudio/
Best match: pyaudio 0.2.8
Downloading http://people.csail.mit.edu/hubert/pyaudio/packages/pyaudio-0.2.8.tar.gz#md5=
Processing pyaudio-0.2.8.tar.gz
Writing /tmp/easy_install-7xXMsw/PyAudio-0.2.8/setup.cfg
Running PyAudio-0.2.8/setup.py -q bdist_egg --dist-dir /tmp/easy_install-7xXMsw/PyAudio-0.2.8/egg-dist-tmp-mkPGUD
warning: no files found matching '*.c' under directory 'test'
src/_portaudiomodule.c:29:10: fatal error: 'portaudio.h' file not found
# include "portaudio.h"

```
     ^
```

1 error generated.
error: Setup script exited with error: command 'cc' failed with exit status 1
## (https://github.com/mofarrell/p2pvc/issues/29)

JARVIS:Desktop admin$  sudo find / -name "portaudio.h"
find: /dev/fd/3: Not a directory
find: /dev/fd/4: Not a directory
/opt/local/include/portaudio.h
## /usr/local/Cellar/portaudio/19.20140130/include/portaudio.h

JARVIS:Desktop admin$ export C_INCLUDE_PATH=/usr/local/Cellar/portaudio/19.20140130/include:/usr/local/include; make clean; make
make: **\* No rule to make target `clean'.  Stop.
make: **\* No targets specified and no makefile found.  Stop.
JARVIS:Desktop admin$ 
JARVIS:Desktop admin$ 

What should I do now ?

**Comment by mofarrell** [comment]
This is not an issue with p2pvc.  Closing the issue.

On a side note you aren't running our makefile as our makefile has a `clean` target.  You are not running make in the right directory: `No targets specified and no makefile found. Stop.`

Make sure to change directory to the p2pvc directory and add `/opt/local/include` to your include path.  If that doesn't work reinstall portaudio.
