### ISSUE TITLE
What is the license applied to this repo?

### ISSUE THREAD

**Issue by ifraixedes** [mofarrell/p2pvc#4]
Hi, 

This repository contains a nice job, however it isn't release without any license or I couldn't find.

Could you consider to add one? people would be clearer if they can use for the purpose that they think.

Many thanks.

**Comment by theSouL** [comment]
Yes, please, I was searching for the same.

**Comment by emgram769** [comment]
added the MIT license

**Comment by ifraixedes** [comment]
Brilliant.
Thanks
