### ISSUE TITLE
Is it possible to set the max character count height and width?

### ISSUE THREAD

**Issue by hh** [mofarrell/p2pvc#7]

**Comment by ghost** [comment]
Tried to change the macro in display.c (200 \* 80 instead of 100 \* 40) and it just segv.
I tried to look a little where the issue could come from, but didnt find it.

**Comment by emgram769** [comment]
@nowahe its almost entirely stack allocated so something that big would definitely get interrupted.

height and width were hard coded to make network communications easier.  If you want to edit the macros in display.c, the client and server need to have the same dimensions.

we'll work on making this automatic (perhaps to fill up the terminal screen), but this involves a couple somewhat large changes in the networking

**Comment by ghost** [comment]
@emgram769 Changed the packet size macro in p2plib.c and worked like a charm. Just have some lag problems but seems network related
